---
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: nova-scheduler
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: nova-scheduler
    spec:
      initContainers:
        - command:
          - kubernetes-entrypoint
          name: init
          image: {{ include "common.images.kubernetes-entrypoint" (dict "registry" .Values.imageRegistry "namespace" .Values.imageNamespace) | quote }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: INTERFACE_NAME
            value: eth0
          - name: DEPENDENCY_JOBS
            value: "nova-db-sync,nova-register"
      containers:
        - name: nova-scheduler
          securityContext:
            privileged: true
          image: {{ template "nova.scheduler.image" . }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          env: 
            - name: KOLLA_CONFIG_STRATEGY
              value: "COPY_ALWAYS"
            - name: KOLLA_SERVICE_NAME
              value: "nova-scheduler"
          volumeMounts:
            - mountPath: /var/log/kolla/nova
              name: kollalog
              mountPropagation: HostToContainer
            - name: nova-etc
              mountPath: /var/lib/kolla/config_files/config.json
              subPath: nova-scheduler.json
            - name: nova-etc
              mountPath: /var/lib/kolla/config_files/nova.conf
              subPath: nova.conf
      serviceAccount: {{ .Values.serviceAccountName}}
      serviceAccountName: {{ .Values.serviceAccountName}}
      volumes:
        - hostPath:
            path: /var/log/kolla/nova
            type: DirectoryOrCreate
          name: kollalog
        - configMap:
            defaultMode: 420
            name: nova-etc
          name: nova-etc

